const games=[{name:'Genshin Impact',spec:'HIGH GPU · 5.2 GB RAM',color:'#6257ff',badge:'DEMANDING',score:72,fps:'48–60 FPS',verdict:'PLAYABLE WITH CARE',title:'Strong start. Watch the heat.',copy:'You have enough power for a smooth session, but prolonged play may create thermal pressure.',ai:'Your iQOO 13 can run Genshin Impact comfortably right now. Memory headroom is healthy, but the current 39°C device temperature means sustained high settings could cause a small FPS dip after 40 minutes.',gain:8},{name:'Call of Duty: Mobile',spec:'HIGH GPU · 3.8 GB RAM',color:'#ff783d',badge:'COMPETITIVE',score:89,fps:'80–120 FPS',verdict:'OPTIMAL',title:'Locked in for the win.',copy:'Your device has excellent headroom for a responsive, high-frame-rate session.',ai:'Your iQOO 13 is in an excellent state for Call of Duty: Mobile. The performance model predicts stable high refresh gameplay with a low thermal risk for the next hour.',gain:4},{name:'Honkai: Star Rail',spec:'HIGH GPU · 4.6 GB RAM',color:'#ed60b2',badge:'DEMANDING',score:76,fps:'52–60 FPS',verdict:'PLAYABLE WITH CARE',title:'Ready with room to breathe.',copy:'A smooth experience is expected, with slight pressure during extended play.',ai:'Honkai: Star Rail will run well now. Closing nonessential apps creates more memory headroom and helps keep your session smooth after the first 30 minutes.',gain:6},{name:'PUBG Mobile',spec:'MEDIUM GPU · 3.1 GB RAM',color:'#ffca52',badge:'COMPETITIVE',score:92,fps:'88–90 FPS',verdict:'OPTIMAL',title:'Battle-ready conditions.',copy:'Thermals and memory are both in the ideal range for high frame-rate play.',ai:'Your current device state is ideal for PUBG Mobile. NEXUS expects stable frame pacing, low heat build-up, and plenty of battery headroom.',gain:3},{name:'Wuthering Waves',spec:'VERY HIGH GPU · 5.8 GB RAM',color:'#6ce1da',badge:'EXTREME',score:65,fps:'42–55 FPS',verdict:'LIMITED HEADROOM',title:'Powerful, but demanding.',copy:'The game is supported, but high settings will push your current thermal envelope.',ai:'Wuthering Waves is one of the most demanding workloads on your device. Lowering shadows to medium and optimizing first will give you the best sustained result.',gain:10},{name:'Asphalt Legends',spec:'MEDIUM GPU · 2.4 GB RAM',color:'#7e97ff',badge:'ARCADE',score:95,fps:'90 FPS',verdict:'OPTIMAL',title:'Smooth road ahead.',copy:'This workload sits comfortably within your device’s current performance window.',ai:'Asphalt Legends is a perfect match for the current state of your iQOO 13. Expect a fluid session with minimal battery and thermal impact.',gain:2}];let selected=games[0],optimized=false,sessionTimer;
const $=s=>document.querySelector(s);function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function renderGames(){const grid=$('#gameGrid');grid.innerHTML=games.map((g,i)=>`<button class="game ${g===selected?'selected':''}" style="--game:${g.color}" data-i="${i}"><div class="game-art"></div><div class="game-content"><span class="badge">${g.badge}</span><h3>${g.name}</h3><p>${g.spec}</p></div></button>`).join('');document.querySelectorAll('.game').forEach(x=>x.onclick=()=>{selected=games[x.dataset.i];optimized=false;renderGames();updateSelection()})}function updateSelection(){$('#selectedName').textContent=selected.name;$('#selectedSpecs').textContent=selected.spec}function risk(title,state,text,color){return `<article class="risk card"><span>${title}</span><h3><i style="background:${color}"></i>${state}</h3><p>${text}</p></article>`}function renderResult(){let s=optimized?Math.min(99,selected.score+selected.gain):selected.score;$('#resultGame').textContent=selected.name.toUpperCase();$('#performanceScore').textContent=s;$('#verdictLabel').textContent=optimized?'OPTIMIZED FOR PLAY':selected.verdict;$('#verdictTitle').textContent=optimized?'Clear the runway. You’re set.':selected.title;$('#verdictCopy').textContent=optimized?`Game Mode is active and background load is reduced. Your expected performance has improved by ${selected.gain} points.`:selected.copy;$('#aiText').textContent=optimized?`NEXUS has created additional headroom for ${selected.name}. Background activity is reduced and Game Mode is ready; enjoy a more stable high-performance session.`:selected.ai;$('#fpsText').textContent=optimized?selected.fps.replace(/(\d+)/,m=>+m+selected.gain):selected.fps;$('#optimizeCopy').textContent=optimized?`Game Mode is active. NEXUS has cleared 3 background processes and is prioritizing this session.`:`Close 3 background processes and activate Game Mode to gain an estimated ${selected.gain} FPS.`;$('#optimizeBtn').textContent=optimized?'✓ PHONE OPTIMIZED':'OPTIMIZE FOR ME →';$('#risks').innerHTML=risk('THERMAL RISK',s>85?'LOW':s>70?'MEDIUM':'HIGH',s>85?'Thermals remain comfortably stable.':'Heat may rise during sustained play.',s>85?'#b8ff58':'#ffb25b')+risk('BATTERY IMPACT',s>85?'LOW':'MEDIUM',s>85?'Efficient workload for current battery.':'Expect roughly 17% per hour.','#9e7aff')+risk('RAM PRESSURE',s>80?'LOW':'MEDIUM',s>80?'Healthy memory headroom available.':'Close background apps for stability.','#b8ff58')+risk('NETWORK COST','1.3 GB / HOUR','Wi‑Fi is recommended for longer sessions.','#ffb25b')}
renderGames();updateSelection();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#runAnalysis').onclick=()=>{renderResult();show('results')};$('#optimizeBtn').onclick=()=>{if(!optimized){optimized=true;renderResult();toast('OPTIMIZATION COMPLETE · +'+selected.gain+' FPS ESTIMATED')}else toast('GAME MODE IS ALREADY ACTIVE')};$('#whyBtn').onclick=()=>toast('MODEL USED 24 TELEMETRY SIGNALS · 94% CONFIDENCE');$('#speakBtn').onclick=()=>{toast('AUDIO BRIEFING READY');if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance($('#aiText').textContent))}};$('#launchBtn').onclick=()=>{show('session');$('#sessionGame').textContent=selected.name;let fps=Math.max(48,selected.score-14+(optimized?selected.gain:0));$('#liveFps').textContent=fps;let temp=optimized?38.6:40.1;let battery=77;clearInterval(sessionTimer);sessionTimer=setInterval(()=>{fps+=Math.round(Math.random()*4-2);temp+=Math.random()*.15; if(Math.random()>.7)battery-=1;$('#liveFps').textContent=fps;$('#liveTemp').textContent=temp.toFixed(1)+'°';$('#sessionBattery').textContent=battery+'%'},2200);toast('GAME MODE ACTIVATED · SESSION STARTED')};$('#endSession').onclick=()=>{clearInterval(sessionTimer);toast('SESSION SAVED TO PERFORMANCE HISTORY');show('dashboard')};

function gb(n){return n==null||isNaN(n)?'—':(Math.round(n*10)/10).toFixed(1)}
function pct(used,total){if(!total)return 0;return Math.max(0,Math.min(100,Math.round(used/total*100)))}
function setNav(ok,msg){const n=$('.nav-pulse');if(!n)return;n.innerHTML=ok?'<span></span> LIVE DEVICE':'<span></span> '+(msg||'DEVICE OFFLINE')}
function renderDevice(d){
  if(!d||!d.connected){setNav(false,d&&d.error?String(d.error).split('.')[0].toUpperCase():'DEVICE OFFLINE');return}
  setNav(true);
  const model=d.model||'Android device';
  const mfr=d.manufacturer||'';
  $('#deviceLabel').textContent=model;
  $('#deviceName').innerHTML=model+' <small id="deviceTag">'+(d.android_version||'')+'</small>';
  $('#deviceMeta').textContent=(mfr?(mfr+' · '):'')+'Android '+(d.android_version||'?');
  if(d.ram_used_gb!=null&&d.ram_total_gb!=null){
    $('#ramText').textContent=gb(d.ram_used_gb)+' / '+gb(d.ram_total_gb)+' GB';
    $('#ramBar').style.width=pct(d.ram_used_gb,d.ram_total_gb)+'%';
  }
  if(d.storage_used_gb!=null&&d.storage_total_gb!=null){
    $('#storageText').textContent=gb(d.storage_used_gb)+' / '+gb(d.storage_total_gb)+' GB';
    $('#storageBar').style.width=pct(d.storage_used_gb,d.storage_total_gb)+'%';
  }
  if(d.battery_percent!=null)$('#batteryText').textContent=Math.round(d.battery_percent)+'%';
  const temp=d.temperature_c;
  const hot=temp!=null&&temp>=42;
  $('#tempText').innerHTML=(temp==null?'—':temp.toFixed(1)+'°C')+' <i class="temp-ok" id="tempDot"></i>';
  const dot=$('#tempDot');if(dot)dot.style.background=hot?'#ffb25b':'';
  const ch=$('#chargingText');
  ch.textContent=d.charging?'⚡ CHARGING':'ON BATTERY';
  ch.classList.toggle('charging',!!d.charging);
}
function pollTelemetry(){
  fetch('/api/telemetry').then(r=>r.json()).then(renderDevice).catch(()=>renderDevice({connected:false,error:'Bridge offline'}));
}
pollTelemetry();
setInterval(pollTelemetry,2000);

